create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  image text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Siapa saja (pengunjung & admin) boleh lihat produk yang aktif.
drop policy if exists "Anyone can view active products" on public.products;
create policy "Anyone can view active products"
on public.products
for select
to anon, authenticated
using (is_active = true);

-- Admin boleh lihat SEMUA produk, termasuk yang nonaktif.
drop policy if exists "Admins can view all products" on public.products;
create policy "Admins can view all products"
on public.products
for select
to authenticated
using ((select is_admin()));

-- Hanya admin yang boleh tambah/ubah/hapus produk.
drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check ((select is_admin()));

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using ((select is_admin()));

-- GRANT: anon cuma boleh SELECT. Admin (authenticated) boleh
-- SELECT/INSERT/UPDATE/DELETE, tetap dibatasi RLS di atas.
revoke all on table public.products from anon;
grant select on table public.products to anon;

revoke all on table public.products from authenticated;
grant select, insert, update, delete on table public.products to authenticated;

-- =========================================================
-- TABEL: orders
-- =========================================================

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  items jsonb not null,
  total numeric not null,
  payment_status text not null default 'Belum Bayar',
  order_status text not null default 'Pesanan Baru',
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- Siapa saja (customer belum login) boleh BIKIN pesanan baru,
-- tapi TIDAK BOLEH baca pesanan siapapun (demi privasi).
drop policy if exists "Anyone can create an order" on public.orders;
create policy "Anyone can create an order"
on public.orders
for insert
to anon, authenticated
with check (true);

-- Hanya admin yang boleh melihat semua pesanan.
drop policy if exists "Admins can view all orders" on public.orders;
create policy "Admins can view all orders"
on public.orders
for select
to authenticated
using ((select is_admin()));

-- Hanya admin yang boleh update status pesanan.
drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders
for update
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

-- Hanya admin yang boleh hapus pesanan.
drop policy if exists "Admins can delete orders" on public.orders;
create policy "Admins can delete orders"
on public.orders
for delete
to authenticated
using ((select is_admin()));

-- GRANT: anon cuma boleh INSERT (tidak bisa baca balik).
-- Admin (authenticated) boleh kelola penuh, tetap dibatasi RLS.
revoke all on table public.orders from anon;
grant insert on table public.orders to anon;

revoke all on table public.orders from authenticated;
grant select, insert, update, delete on table public.orders to authenticated;

-- Dipakai oleh:
-- - src/app.js & index.html (situs customer)
-- - admin/dashboard.js (preview tabel admin)
-- =========================================================