-- =========================================================
-- KOPI NGALAM — Tahap 3: Akuntansi (Bahan Baku, Resep, Pengeluaran)
-- =========================================================
-- Tujuan file ini:
-- 1. Mendokumentasikan skema akuntansi yang sebelumnya dibuat
--    langsung lewat SQL Editor (belum pernah disimpan di repo).
-- 2. MEMPERBAIKI trigger pengurangan stok otomatis (trg_kurangi_stok)
--    yang masih mengacu ke tabel lama `product_ingredients`,
--    padahal tab "Resep Menu" sekarang memakai `recipes` +
--    `recipe_items` (dengan konversi satuan kg->gram, dll).

-- ---------------------------------------------------------
-- 1. INGREDIENTS (Bahan Baku)
-- ---------------------------------------------------------
create table if not exists public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,                    -- satuan besar/stok, misal: kg, L, pcs
  recipe_unit text not null default 'gram', -- satuan resep, misal: gram, ml, pcs
  conversion_factor numeric not null default 1, -- 1 unit besar = berapa recipe_unit
  stock_quantity numeric not null default 0,
  cost_per_unit numeric not null default 0, -- harga per satuan besar (unit)
  low_stock_threshold numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Jaga-jaga kalau tabel sudah ada dari versi lama tanpa kolom ini:
alter table public.ingredients add column if not exists recipe_unit text not null default 'gram';
alter table public.ingredients add column if not exists conversion_factor numeric not null default 1;
alter table public.ingredients add column if not exists low_stock_threshold numeric not null default 0;
alter table public.ingredients add column if not exists updated_at timestamptz not null default now();

alter table public.ingredients enable row level security;

drop policy if exists "Admins can manage ingredients" on public.ingredients;
create policy "Admins can manage ingredients"
on public.ingredients
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.ingredients from anon;
revoke all on table public.ingredients from authenticated;
grant select, insert, update, delete on table public.ingredients to authenticated;

-- ---------------------------------------------------------
-- 2. INGREDIENT_PURCHASES (Riwayat pembelian bahan)
-- ---------------------------------------------------------
create table if not exists public.ingredient_purchases (
  id bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  purchase_date date not null default current_date,
  quantity numeric not null,       -- jumlah dibeli, satuan besar
  total_price numeric not null,
  unit_price numeric not null,     -- total_price / quantity
  created_at timestamptz not null default now()
);

alter table public.ingredient_purchases enable row level security;

drop policy if exists "Admins can manage purchases" on public.ingredient_purchases;
create policy "Admins can manage purchases"
on public.ingredient_purchases
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.ingredient_purchases from anon;
revoke all on table public.ingredient_purchases from authenticated;
grant select, insert, update, delete on table public.ingredient_purchases to authenticated;

-- Trigger: setiap ada pembelian baru -> stok bahan bertambah & harga terbaru dipakai
create or replace function public.tambah_stok_dari_pembelian()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ingredients
  set stock_quantity = stock_quantity + new.quantity,
      cost_per_unit = new.unit_price,
      updated_at = now()
  where id = new.ingredient_id;

  return new;
end;
$$;

drop trigger if exists trg_tambah_stok_pembelian on public.ingredient_purchases;
create trigger trg_tambah_stok_pembelian
after insert on public.ingredient_purchases
for each row
execute function public.tambah_stok_dari_pembelian();

-- ---------------------------------------------------------
-- 3. RECIPES & RECIPE_ITEMS (Resep tiap menu, skema baru)
-- ---------------------------------------------------------
create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  product_id bigint not null unique references public.products(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.recipes enable row level security;

drop policy if exists "Admins can manage recipes" on public.recipes;
create policy "Admins can manage recipes"
on public.recipes
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.recipes from anon;
revoke all on table public.recipes from authenticated;
grant select, insert, update, delete on table public.recipes to authenticated;

create table if not exists public.recipe_items (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  quantity_used numeric not null, -- dalam recipe_unit bahan tsb
  unique (recipe_id, ingredient_id)
);

alter table public.recipe_items enable row level security;

drop policy if exists "Admins can manage recipe items" on public.recipe_items;
create policy "Admins can manage recipe items"
on public.recipe_items
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.recipe_items from anon;
revoke all on table public.recipe_items from authenticated;
grant select, insert, update, delete on table public.recipe_items to authenticated;

-- (Opsional) Tabel lama product_ingredients tidak dipakai lagi oleh aplikasi.
-- Sengaja TIDAK di-drop otomatis di sini demi keamanan data.
-- Kalau sudah yakin tidak dipakai, boleh dihapus manual:
-- drop table if exists public.product_ingredients;

-- ---------------------------------------------------------
-- 4. EXPENSE_CATEGORIES & EXPENSES (Pengeluaran operasional)
-- ---------------------------------------------------------
create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.expense_categories enable row level security;

drop policy if exists "Admins can manage expense categories" on public.expense_categories;
create policy "Admins can manage expense categories"
on public.expense_categories
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.expense_categories from anon;
revoke all on table public.expense_categories from authenticated;
grant select, insert, update, delete on table public.expense_categories to authenticated;

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  category_id bigint references public.expense_categories(id) on delete set null,
  description text,
  amount numeric not null,
  expense_date date not null default current_date,
  created_at timestamptz not null default now()
);

-- Jaga-jaga kalau tabel expenses versi lama masih pakai kolom `category` (text):
alter table public.expenses add column if not exists category_id bigint references public.expense_categories(id) on delete set null;

alter table public.expenses enable row level security;

drop policy if exists "Admins can manage expenses" on public.expenses;
create policy "Admins can manage expenses"
on public.expenses
for all
to authenticated
using ((select is_admin()))
with check ((select is_admin()));

revoke all on table public.expenses from anon;
revoke all on table public.expenses from authenticated;
grant select, insert, update, delete on table public.expenses to authenticated;

-- ---------------------------------------------------------
-- 5. FIX: Trigger pengurangan stok otomatis saat pesanan masuk
--    (sebelumnya salah baca dari product_ingredients, sekarang
--     pakai recipes + recipe_items + conversion_factor)
-- ---------------------------------------------------------
create or replace function public.kurangi_stok_bahan()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_product_id bigint;
  v_qty numeric;
begin
  for item in select * from jsonb_array_elements(new.items)
  loop
    v_product_id := (item->>'product_id')::bigint;
    v_qty := (item->>'quantity')::numeric;

    if v_product_id is not null and v_qty is not null then
      update public.ingredients ing
      set stock_quantity = ing.stock_quantity - (
            (ri.quantity_used / nullif(ing.conversion_factor, 0)) * v_qty
          ),
          updated_at = now()
      from public.recipe_items ri
      join public.recipes r on r.id = ri.recipe_id
      where ri.ingredient_id = ing.id
        and r.product_id = v_product_id;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists trg_kurangi_stok on public.orders;
create trigger trg_kurangi_stok
after insert on public.orders
for each row
execute function public.kurangi_stok_bahan();

-- ---------------------------------------------------------
-- VERIFIKASI
-- ---------------------------------------------------------
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'ingredients', 'ingredient_purchases',
    'recipes', 'recipe_items',
    'expense_categories', 'expenses'
  );

select trigger_name, event_manipulation, event_object_table
from information_schema.triggers
where trigger_name in ('trg_kurangi_stok', 'trg_tambah_stok_pembelian');